# Generated by Django 4.2.13 on 2026-07-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='categorie',
            field=models.CharField(choices=[('AGREMENT', 'Agrement'), ('AUTORISATION', 'Autorisation environnementale'), ('CONTRAT', 'Contrat'), ('RAPPORT', 'Rapport'), ('DECLARATION', 'Declaration'), ('CORRESPONDANCE', 'Correspondance officielle'), ('JURIDIQUE', 'Document juridique'), ('TECHNIQUE', 'Document technique'), ('PROFORMA', 'Proforma'), ('BC', 'Bon de Commande'), ('BL', 'Bon de Livraison'), ('FACTURE', 'Facture'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20),
        ),
    ]
