# Generated by Django 4.2.13 on 2026-06-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operateur',
            name='type_operateur',
            field=models.CharField(choices=[('GENERATEUR', 'Générateur de déchets'), ('TRANSPORTEUR', 'Transporteur de déchets'), ('ELIMINATEUR', 'Éliminateur de déchets'), ('VALORISATEUR', 'Valorisateur de déchets'), ('CET', "Centre d'Enfouissement Technique"), ('DIR_WILAYA', "Direction de l'Environnement Wilaya"), ('MINISTERE', "Ministère de l'Environnement")], max_length=20),
        ),
    ]
