# Generated by Django 4.2.13 on 2026-06-28 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recuperateurs', '0001_initial'),
        ('operateurs', '0002_alter_operateur_type_operateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='operateur',
            name='recuperateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operateurs', to='recuperateurs.recuperateur'),
        ),
    ]
