# Generated by Django 4.2.13 on 2026-06-25 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operateurs', '0002_alter_operateur_type_operateur'),
        ('traceability', '0003_traceability_couleur_traceability_niveau_proprete'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceability',
            name='cet',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_operateur': 'CET'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traceability_cet', to='operateurs.operateur'),
        ),
        migrations.AddField(
            model_name='traceability',
            name='quantite_enfouie',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='traceability',
            name='destination_type',
            field=models.CharField(choices=[('VALORISATION', 'Valorisation'), ('ELIMINATION', 'Élimination (DSD)'), ('STOCKAGE', 'Stockage temporaire'), ('RECYCLAGE', 'Recyclage'), ('CET', "Centre d'Enfouissement Technique")], default='VALORISATION', max_length=20),
        ),
    ]
