# Generated by Django 4.2.13 on 2026-09-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0010_traceability_prix_revient_global_ttc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceability',
            name='adresse_enlevement',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='traceability',
            name='caracteristiques_danger',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='traceability',
            name='conditionnement',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='traceability',
            name='date_collecte_prevue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traceability',
            name='date_depart',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traceability',
            name='date_enlevement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traceability',
            name='date_reception',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traceability',
            name='designation_ar',
            field=models.CharField(blank=True, max_length=300, verbose_name='Désignation (arabe)'),
        ),
        migrations.AddField(
            model_name='traceability',
            name='etat_physique',
            field=models.CharField(blank=True, choices=[('SOLIDE', 'Solide'), ('LIQUIDE', 'Liquide'), ('BOUEUX', 'Boueux / Pâteux'), ('GAZEUX', 'Gazeux')], max_length=15),
        ),
        migrations.AddField(
            model_name='traceability',
            name='id_recup_dz',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Récup DZ'),
        ),
        migrations.AddField(
            model_name='traceability',
            name='incident',
            field=models.CharField(blank=True, choices=[('ACCIDENT', 'Accident'), ('FUITE', 'Fuite'), ('PERTE', 'Perte de chargement'), ('RETARD', 'Retard important')], max_length=15),
        ),
        migrations.AddField(
            model_name='traceability',
            name='itineraire',
            field=models.CharField(blank=True, max_length=300, verbose_name='Itinéraire prévu'),
        ),
        migrations.AddField(
            model_name='traceability',
            name='lieu_depart',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='traceability',
            name='lieu_stockage',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='traceability',
            name='motif_refus',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='traceability',
            name='ordre_enlevement',
            field=models.CharField(blank=True, max_length=100, verbose_name="N° Ordre d'enlèvement"),
        ),
        migrations.AddField(
            model_name='traceability',
            name='quantite_acceptee',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='traceability',
            name='quantite_chargee',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='traceability',
            name='quantite_refusee',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='traceability',
            name='transporteur_agrement',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° Agrément transporteur'),
        ),
        migrations.AddField(
            model_name='traceability',
            name='transporteur_date_agrement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traceability',
            name='transporteur_statut_agrement',
            field=models.CharField(blank=True, choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré')], max_length=10),
        ),
        migrations.AddField(
            model_name='traceability',
            name='type_engin',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
