# Generated by Django 4.2.13 on 2026-07-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email client'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='client_fax',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fax client'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='client_nif',
            field=models.CharField(blank=True, max_length=100, verbose_name='NIF client'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='client_nis',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° I.S. client'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='client_numero_article',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° Article client'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='client_rc',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° RC client'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='client_telephone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tél. client'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='date_echeance',
            field=models.DateField(blank=True, null=True, verbose_name='Échéance'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='pieces_liees',
            field=models.CharField(blank=True, max_length=200, verbose_name='Pièces liées'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='ref_client',
            field=models.CharField(blank=True, max_length=100, verbose_name='Réf. client'),
        ),
    ]
