# Generated by Django 4.2.13 on 2026-07-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0002_boncommande_client_email_boncommande_client_fax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='type_document',
            field=models.CharField(choices=[('BC', 'Bon de Commande'), ('PROFORMA', 'Proforma')], default='BC', max_length=10),
        ),
    ]
