# Generated by Django 4.2.13 on 2026-07-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0003_boncommande_type_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='mode_paiement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='reference_paiement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence de paiement'),
        ),
        migrations.AlterField(
            model_name='boncommande',
            name='type_document',
            field=models.CharField(choices=[('BC', 'Bon de Commande'), ('PROFORMA', 'Proforma'), ('FACTURE', 'Facture')], default='BC', max_length=10),
        ),
    ]
