# Generated by Django 4.2.13 on 2026-07-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0004_boncommande_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boncommande',
            name='numero',
            field=models.CharField(help_text="Saisi par l'utilisateur, ex: CM20260003 / PR20260003 / FA20260003", max_length=30, unique=True, verbose_name='N° document'),
        ),
    ]
