# Generated by Django 4.2.13 on 2026-07-09 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0005_alter_bonlivraison_numero'),
        ('bc', '0005_alter_boncommande_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='bon_livraison_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factures_generees', to='bl.bonlivraison', verbose_name="BL d'origine"),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='proforma_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bc_generes', to='bc.boncommande', verbose_name="Proforma d'origine"),
        ),
        migrations.CreateModel(
            name='DocumentCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=5)),
                ('year', models.PositiveIntegerField()),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Compteur de document',
                'verbose_name_plural': 'Compteurs de document',
                'unique_together': {('prefix', 'year')},
            },
        ),
    ]
