# Generated by Django 4.2.13 on 2026-07-09 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0006_bonlivraison_bon_commande_origine'),
        ('bc', '0006_boncommande_bon_livraison_origine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boncommande',
            name='bon_livraison_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_generees', to='bl.bonlivraison', verbose_name="BL d'origine"),
        ),
        migrations.AlterField(
            model_name='boncommande',
            name='proforma_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bc_generes', to='bc.boncommande', verbose_name="Proforma d'origine"),
        ),
    ]
