# Generated by Django 4.2.13 on 2026-07-09 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operateurs', '0005_add_convention_cet'),
        ('bc', '0007_alter_boncommande_bon_livraison_origine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='client_operateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_commande_clients', to='operateurs.operateur', verbose_name='Client (fiche opérateur)'),
        ),
    ]
