# Generated by Django 4.2.13 on 2026-07-09 22:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0008_boncommande_client_operateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='dossier_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text="Identifiant partagé par tous les documents d'une même opération (Proforma → BC → BL → Facture) — hérité automatiquement lors de la génération d'un document à partir d'un autre.", verbose_name='Dossier'),
        ),
    ]
