# Generated by Django 4.2.13 on 2026-07-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0011_fix_shared_dossier_id_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='validite_offre_jours',
            field=models.PositiveIntegerField(blank=True, help_text="Proforma uniquement : durée de validité de l'offre, en jours.", null=True, verbose_name="Validité de l'offre (jours)"),
        ),
    ]
