# Generated by Django 4.2.13 on 2026-07-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperateurs', '0002_recuperateur_logo_recuperateur_numero_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='recuperateur',
            name='compte_bancaire',
            field=models.CharField(blank=True, max_length=100, verbose_name='Compte bancaire (RIB)'),
        ),
        migrations.AddField(
            model_name='recuperateur',
            name='fax',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
