# Generated by Django 4.2.13 on 2026-07-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperateurs', '0003_recuperateur_compte_bancaire_recuperateur_fax'),
    ]

    operations = [
        migrations.AddField(
            model_name='recuperateur',
            name='cachet_electronique',
            field=models.ImageField(blank=True, null=True, upload_to='recuperateurs/cachets/', verbose_name='Cachet électronique'),
        ),
        migrations.AddField(
            model_name='recuperateur',
            name='signature_electronique',
            field=models.ImageField(blank=True, null=True, upload_to='recuperateurs/signatures/', verbose_name='Signature électronique'),
        ),
    ]
