# Generated by Django 4.2.13 on 2026-07-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperateurs', '0004_recuperateur_cachet_electronique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recuperateur',
            name='iso_14001',
            field=models.ImageField(blank=True, null=True, upload_to='recuperateurs/iso/', verbose_name='Certification ISO 14001:2015'),
        ),
        migrations.AddField(
            model_name='recuperateur',
            name='iso_45001',
            field=models.ImageField(blank=True, null=True, upload_to='recuperateurs/iso/', verbose_name='Certification ISO 45001:2018'),
        ),
        migrations.AddField(
            model_name='recuperateur',
            name='iso_9001',
            field=models.ImageField(blank=True, null=True, upload_to='recuperateurs/iso/', verbose_name='Certification ISO 9001:2015'),
        ),
    ]
