# Generated by Django 4.2.13 on 2026-09-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperateurs', '0005_recuperateur_iso_14001_recuperateur_iso_45001_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recuperateur',
            name='capital_social',
            field=models.CharField(blank=True, max_length=100, verbose_name='Capital social (documents PDF/Word)'),
        ),
        migrations.AddField(
            model_name='recuperateur',
            name='slogan',
            field=models.CharField(blank=True, max_length=200, verbose_name='Slogan (documents PDF/Word)'),
        ),
    ]
