# Generated by Django 4.2.13 on 2026-06-29 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operateurs', '0004_assigner_operateurs_existants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recuperateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('destinataire_type', models.CharField(choices=[('ELIMINATEUR', 'Éliminateur de déchets'), ('VALORISATEUR', 'Valorisateur de déchets')], max_length=20)),
                ('date_livraison', models.DateField()),
                ('bon_commande_numero', models.CharField(blank=True, max_length=50)),
                ('date_commande', models.DateField(blank=True, null=True)),
                ('lignes', models.JSONField(blank=True, default=list)),
                ('etabli_par', models.CharField(blank=True, max_length=200)),
                ('qualite', models.JSONField(blank=True, default=dict)),
                ('garantie_alimentaire', models.BooleanField(default=False)),
                ('chauffeur_nom', models.CharField(blank=True, max_length=200)),
                ('camion_numero', models.CharField(blank=True, max_length=50)),
                ('camion_immatriculation', models.CharField(blank=True, max_length=50)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EMIS', 'Émis'), ('VALIDE', 'Validé'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=15)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_livraison_recus', to='operateurs.operateur')),
                ('recuperateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_livraison', to='recuperateurs.recuperateur')),
            ],
            options={
                'verbose_name': 'Bon de Livraison',
                'ordering': ['-created_at'],
            },
        ),
    ]
