# Generated by Django 4.2.13 on 2026-07-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0003_add_cet_destinataire_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonlivraison',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email client'),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='client_fax',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fax client'),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='client_nif',
            field=models.CharField(blank=True, max_length=100, verbose_name='NIF client'),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='client_nis',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° I.S. client'),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='client_numero_article',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° Article client'),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='client_rc',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° RC client'),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='client_telephone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tél. client'),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='mode_livraison',
            field=models.CharField(choices=[('ENLEVEMENT', 'Enlèvement'), ('LIVRAISON', 'Livraison')], default='ENLEVEMENT', max_length=15, verbose_name='Mode de livraison'),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='montant_reference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Montant de référence (DZD)'),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='pieces_liees',
            field=models.CharField(blank=True, max_length=200, verbose_name='Pièces liées'),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='ref_client',
            field=models.CharField(blank=True, max_length=100, verbose_name='Réf. client'),
        ),
    ]
