# Generated by Django 4.2.13 on 2026-07-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0004_bonlivraison_client_email_bonlivraison_client_fax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonlivraison',
            name='numero',
            field=models.CharField(help_text="Saisi par l'utilisateur, ex: BL20260003", max_length=30, unique=True, verbose_name='N° document'),
        ),
    ]
