# Generated by Django 4.2.13 on 2026-07-09 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0006_boncommande_bon_livraison_origine_and_more'),
        ('bl', '0005_alter_bonlivraison_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonlivraison',
            name='bon_commande_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bl_generes', to='bc.boncommande', verbose_name="BC d'origine"),
        ),
    ]
