# Generated by Django 4.2.13 on 2026-07-09 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0007_alter_boncommande_bon_livraison_origine_and_more'),
        ('bl', '0006_bonlivraison_bon_commande_origine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonlivraison',
            name='bon_commande_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bl_generes', to='bc.boncommande', verbose_name="BC d'origine"),
        ),
    ]
