# Generated by Django 4.2.13 on 2026-07-09 22:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0007_alter_bonlivraison_bon_commande_origine'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonlivraison',
            name='dossier_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text="Identifiant partagé par tous les documents d'une même opération (Proforma → BC → BL → Facture).", verbose_name='Dossier'),
        ),
    ]
