# Generated by Django 4.2.13 on 2026-06-24 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignationDechet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_recup_dz', models.CharField(help_text='Identifiant interne — ex: PLA-001, BOIS-012', max_length=20, unique=True)),
                ('designation', models.CharField(help_text="ex: Bouteille d'eau PET", max_length=300)),
                ('matiere', models.CharField(blank=True, help_text='ex: PET, PEHD, BOIS, Acier', max_length=100)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='nomenclature.nomenclature')),
            ],
            options={
                'verbose_name': 'Désignation de déchet',
                'verbose_name_plural': 'Désignations de déchets',
                'ordering': ['nomenclature__code', 'ordre', 'designation'],
            },
        ),
    ]
