# Generated by Django 4.2.13 on 2026-07-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0002_designationdechet'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='annexe',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
